### ISSUE TITLE
Cross contract logic not available

### ISSUE THREAD

**Issue by thor314** [snjax/nep4_nostd_example#1]
Hey, nice repo. I've been playing around with it, just noticed `ext_contract` isn't functional yet.

```
use near_sdk_pure::{ext_contract, };
#[ext_contract(smthn)]
pub trait Something {
}
```

errors:
```
7 | #[ext_contract(smthn)]
  | ^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `std`
  |
  = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I'm also referencing this repo from one of mine. https://github.com/thor314/near-no-std-template. Thx for the work.

If you'd prefer, I can move this comment to https://github.com/snjax/near-sdk-pure-rs here.

**Comment by snjax** [comment]
Hi, @thor314 . Thank you for the bug report. I have not tested it for ext_contract.
Here is the fix https://github.com/snjax/near-sdk-pure-rs/pull/1/commits/9806632aec8006b6c2bd1950207643b1c853816c
